#!/usr/bin/env python

from zhipuai import ZhipuAI
from colorama import Fore, Style
import sys

def main():
    client = ZhipuAI(api_key="2912857228b2930e8669c3138f3a3753.91jfFT0NGUWu555L") 
    if len(sys.argv) == 1:

        while(1):
            print(Fore.LIGHTYELLOW_EX+"Chat>",end='')
            print(Style.RESET_ALL, end='')
            content=input()
            if(content=='q'):
                print(Fore.LIGHTRED_EX+"Quit Chat"+Style.RESET_ALL)
                exit()
            response = client.chat.completions.create(
                model="glm-4",  
                messages=[
                    {"role": "user", "content": content},
                ],
                stream=True,
            )
            print(Fore.LIGHTBLUE_EX+"User: ",end='')
            print(Style.RESET_ALL)
            print(content)
            print(Fore.LIGHTGREEN_EX+"Assistant: ",end='')
            print(Style.RESET_ALL)
            for chunk in response:
                print(chunk.choices[0].delta.content,end='')
            print("\n(end)")
    
    else:
        content=''
        for arg in sys.argv[1:]:
            content+=arg+" "
        
        response = client.chat.completions.create(
            model="glm-4",  
            messages=[
                {"role": "user", "content": content},
            ],
            stream=True,
        )
        print(Fore.LIGHTBLUE_EX+"User: ",end='')
        print(Style.RESET_ALL)
        print(content)
        print(Fore.LIGHTGREEN_EX+"Assistant: ",end='')
        print(Style.RESET_ALL)
        for chunk in response:
            print(chunk.choices[0].delta.content,end='')
        print("\n(end)")

if __name__ == "__main__":
    main()
