#!/usr/bin/env python3

from zhipuai import ZhipuAI
from colorama import Fore, Style
import sys

def main():
    client = ZhipuAI(api_key="******" )
    if len(sys.argv) == 1:
        messages=[]
        while(1):
            print(Fore.LIGHTYELLOW_EX+"Chat>",end='')
            print(Style.RESET_ALL, end='')
            user_content=input()
            if(user_content=='q'):
                print(Fore.LIGHTRED_EX+"Quit Chat"+Style.RESET_ALL)
                exit()
            messages.append({"role": "user", "content": user_content})
            response = client.chat.completions.create(
                model="glm-4",  
                messages=messages,
                stream=True,
            )
            print(Fore.LIGHTBLUE_EX+"User: ",end='')
            print(Style.RESET_ALL)
            print(user_content)
            print(Fore.LIGHTGREEN_EX+"Assistant: ",end='')
            print(Style.RESET_ALL)
            assistant_conntent=""
            for chunk in response:
                assistant_conntent+=chunk.choices[0].delta.content
                print(chunk.choices[0].delta.content,end='')
            messages.append({"role": "assistant", "content": assistant_conntent})
            print("\n(end)")
    
    else:
        user_content=''
        for arg in sys.argv[1:]:
            user_content+=arg+" "
        
        response = client.chat.completions.create(
            model="glm-4",  
            messages=[
                {"role": "user", "content": user_content},
            ],
            stream=True,
        )
        print(Fore.LIGHTBLUE_EX+"User: ",end='')
        print(Style.RESET_ALL)
        print(user_content)
        print(Fore.LIGHTGREEN_EX+"Assistant: ",end='')
        print(Style.RESET_ALL)
        for chunk in response:
            print(chunk.choices[0].delta.content,end='')
        print("\n(end)")

if __name__ == "__main__":
    main()
